- name: Установить nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Установить git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Скопировать конфигурационный файл nginx с шаблона
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Перезапустить nginx

- name: Запустить и включить nginx
  service:
    name: nginx
    state: started
    enabled: yes

