services:
  ssh-server:
    image: debian:latest
    container_name: ssh_container
    restart: unless-stopped
    ports:
      - "2222:22"
    volumes:
      - ssh_data:/root
    command: >
      bash -c "apt update && apt install -y openssh-server && 
               mkdir -p /run/sshd && 
               echo 'root:root' | chpasswd && 
               /usr/sbin/sshd -D"
    tty: true

  ssh-server2:
    image: debian:latest
    container_name: ssh_container2
    restart: unless-stopped
    ports:
      - "2223:22"
      - "80:80"
    volumes:
      - ssh_data:/root
    command: >
      bash -c "apt update && apt install -y openssh-server && 
               mkdir -p /run/sshd && 
               echo 'root:root' | chpasswd && 
               /usr/sbin/sshd -D"
    tty: true

volumes:
  ssh_data: